require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
